ALTER TABLE active_timers
    ADD COLUMN IF NOT EXISTS is_paused BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS accumulated_seconds INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_resume_timestamp TIMESTAMPTZ;
