services:
  agency-os:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agency-os
    restart: always
    env_file:
      - .env
    networks:
      - agency-os-net
      - keycloak-net

networks:
  agency-os-net:
    external: true
  keycloak-net:
    external: true
